### ISSUE TITLE
Animation not triggering in instanced content

### ISSUE THREAD

**Issue by SipuliSoppa** [agaertner/bhm-fail-screens#29]
Hey, I was just wondering is the addon supposto to work is instanced content or no?
At least I can't get it to trigger while in instance, works perfectly in open world.
If it is disabled for a reason would it possible to add setting for that enable or disable usage in instanced content

**Comment by agaertner** [comment]
This module checks if a certain music file is being in use by GW2 to know that you are defeated. In certain instances, like SAB, the game is not playing custom defeated music hence that file is never in use. For such cases you need to install ArcDps with the ArcDPS-BlishHUD addon (arcdps_bhud.dll). If the ArcDPS BlishHUD bridge is connected it will use that to detect your defeated state.

**Comment by SipuliSoppa** [comment]
Alrigjht thank you for the explanation and sorry for creating false ticket
Issue has been resolved!
